### ISSUE TITLE
Errors on mfw setup if use Windows (mvm-windows)

### ISSUE THREAD

**Issue by Softovick** [microservice-framework/mfw-cli#10]
<img width="534" alt="2018-02-22" src="https://user-images.githubusercontent.com/441054/36512554-05a220b0-177c-11e8-960b-429d3a0c15df.png">
You need to change the setup procedure, because there are no "xargs" in Windows. And using Linux subsystem is not always possible (and it did not help me).
Look line 765 in file MFWCliClass.js

**Comment by Gormartsen** [comment]
@Softovick 
Could you test it please?

To test, you need to install mfw from GitHub via:
```sh
npm install github:microservice-framework/mfw-cli -g
```

After that try to install any service

**Comment by Gormartsen** [comment]
new fix implemented in master branch. Need a help to test

**Comment by Gormartsen** [comment]
credits to @Softovick for WIN OS testing!
Fixed now.
